version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d products -U user"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
      image:  adminer
      ports:
        - "8081:8080"

#see from h00:m38
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    entrypoint:
      - bash
      - "entrypoint.sh"
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
      - "--port=5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://user:example@pg:5432/products"
    ports:
      - "80:5000"
    depends_on:
      pg:
       condition: service_healthy


volumes:
  db-data:
