# Generated by Django 4.0 on 2024-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('discountPercentage', models.FloatField()),
                ('rating', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
